feat: add docker.io to image
lenra-io/template-node pull request #6
Opened 2022-10-12 13:15 UTC by pichoemr

#__ 

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [ ] I added/updated the documentation about my changes
- [ ] I made my own code-review before requesting one

## Description of the changes

## Technical highlight/advice

2022-10-12 13:21 UTC, shiipou requested changes
That's not much, but there's no point in pushing an indentation change.

2022-10-12 13:21 UTC, shiipou commented on lenra.yml
> +      - "!/widgets/"
```suggestion
    - "**"
    - "!/*.json"
    - "!/server.js"
    - "!/index.js"
    - "!/listeners/"
    - "!/resources/"
    - "!/services/"
    - "!/widgets/"
```

2022-10-12 13:21 UTC, shiipou commented on lenra.yml
> +      - npm i --omit=dev
```suggestion
    - npm i --omit=dev
```

2022-10-12 13:21 UTC, shiipou commented on lenra.yml
> +      - .
```suggestion
    - .
```

2022-10-12 13:21 UTC, shiipou commented on lenra.yml
> +        - chown -R 1000 /app
```suggestion
      - chown -R 1000 /app
```

2022-10-12 13:28 UTC, jonas-martinez approved these changes

2022-10-24 07:33 UTC, pichoemr commented
@shiipou it is vs code which makes the automatic indent, the indentation will be in each PR which touches yml, maybe let it

2022-10-24 08:44 UTC, shiipou approved these changes

2022-10-24 09:02 UTC, merged